---
- hosts: all
  tasks: 
    - name: "Copying hadoop file"
      copy: 
        src: "/root/ansiblews/task11/hadoop-1.2.1-1.x86_64.rpm"
        dest: "/root/"
    - name: "Copying the java files"
      copy: 
        src: "/root/ansiblews/task11/jdk-8u171-linux-x64.rpm"
        dest: "/root/"
    - name: "Installing java"
      command: 
        cmd: "rpm -ivh /root/jdk-8u171-linux-x64.rpm"

    - name: "Installing the hadoop"
      command: 
       cmd: "rpm -ivh /root/hadoop-1.2.1-1.x86_64.rpm --force"
    
